apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: __ENVIRONMENT__ops-agent-eks
  annotations:
    # IRSA annotation - role ARN substituted by deploy-all.sh
    eks.amazonaws.com/role-arn: arn:aws:iam::__ACCOUNT_ID__:role/__ENVIRONMENT__ops-agent-eks-__ENVIRONMENT__-fluent-bit-role
