apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: payment-demo
  labels:
    app.kubernetes.io/name: payment-processor
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: payment-processor
