import * as cdk from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

/**
 * Data Stack
 *
 * Holds the persistent state for the demo:
 *   - DynamoDB `prowler-security-findings` — one item per Prowler finding.
 *     Partition key: finding_uid (Prowler's stable hash of check + resource).
 *     GSI severity-index: severity (PK) + last_seen_at (SK) — "top criticals now".
 *     GSI status-index:   status   (PK) + severity      (SK) — "open by severity".
 *
 *   - S3 `prowler-raw-reports` — raw OCSF JSON uploaded by the Fargate scanner.
 *     A notification on ObjectCreated fires the ingest Lambda (wired in IngestStack).
 *
 *   - S3 `prowler-remediations` — markdown remediation playbooks generated by
 *     Bedrock Nova Lite 2 for HIGH/CRITICAL findings. Read by the dashboard via
 *     presigned URLs.
 */
export class DataStack extends cdk.Stack {
  public readonly findingsTable: dynamodb.Table;
  public readonly costEventsTable: dynamodb.Table;
  public readonly rawReportsBucket: s3.Bucket;
  public readonly remediationsBucket: s3.Bucket;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // One row per billable action the demo performs (Bedrock invocation,
    // DevOps Agent dispatch, Fargate scan…). The Cost page queries this table
    // to render a live stream of spend. TTL=90d keeps the table small.
    this.costEventsTable = new dynamodb.Table(this, 'CostEventsTable', {
      tableName: 'prowler-security-cost-events',
      partitionKey: { name: 'event_id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      encryption: dynamodb.TableEncryption.AWS_MANAGED,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      timeToLiveAttribute: 'ttl',
    });
    // Partition under a single key so we can scan the most recent events
    // ordered by timestamp without a full table scan.
    this.costEventsTable.addGlobalSecondaryIndex({
      indexName: 'by-date',
      partitionKey: { name: 'partition_key', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
    });

    this.findingsTable = new dynamodb.Table(this, 'FindingsTable', {
      tableName: 'prowler-security-findings',
      partitionKey: { name: 'finding_uid', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      encryption: dynamodb.TableEncryption.AWS_MANAGED,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    this.findingsTable.addGlobalSecondaryIndex({
      indexName: 'severity-index',
      partitionKey: { name: 'severity', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'last_seen_at', type: dynamodb.AttributeType.STRING },
    });

    this.findingsTable.addGlobalSecondaryIndex({
      indexName: 'status-index',
      partitionKey: { name: 'status', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'severity', type: dynamodb.AttributeType.STRING },
    });

    this.rawReportsBucket = new s3.Bucket(this, 'RawReportsBucket', {
      bucketName: `prowler-security-raw-reports-${cdk.Aws.ACCOUNT_ID}-${cdk.Aws.REGION}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      versioned: false,
      autoDeleteObjects: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      eventBridgeEnabled: false,
      lifecycleRules: [
        { id: 'expire-raw-after-90-days', expiration: cdk.Duration.days(90) },
      ],
    });

    this.remediationsBucket = new s3.Bucket(this, 'RemediationsBucket', {
      bucketName: `prowler-security-remediations-${cdk.Aws.ACCOUNT_ID}-${cdk.Aws.REGION}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      versioned: false,
      autoDeleteObjects: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      // Browser fetches remediation markdown via presigned URL — CORS required.
      cors: [
        {
          allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.HEAD],
          allowedOrigins: ['*'],
          allowedHeaders: ['*'],
          exposedHeaders: ['ETag', 'Content-Type'],
          maxAge: 300,
        },
      ],
    });

    new cdk.CfnOutput(this, 'FindingsTableName', {
      value: this.findingsTable.tableName,
      description: 'DynamoDB table holding Prowler findings',
    });
    new cdk.CfnOutput(this, 'CostEventsTableName', {
      value: this.costEventsTable.tableName,
      description: 'DynamoDB table holding per-invocation cost events',
    });
    new cdk.CfnOutput(this, 'RawReportsBucketName', {
      value: this.rawReportsBucket.bucketName,
      description: 'S3 bucket where the Fargate scanner uploads raw OCSF JSON',
    });
    new cdk.CfnOutput(this, 'RemediationsBucketName', {
      value: this.remediationsBucket.bucketName,
      description: 'S3 bucket where Bedrock-generated remediation markdown is stored',
    });
  }
}
