apiVersion: v1
kind: Service
metadata:
  name: merchant-gateway-nlb
  namespace: payment-demo
  labels:
    app.kubernetes.io/name: merchant-gateway
    app.kubernetes.io/component: api-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Project=devops-agent-eks,Environment=dev"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: merchant-gateway
