import { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Header,
  SpaceBetween,
  Table,
  TextFilter,
  Pagination,
  Badge,
  StatusIndicator,
  Spinner,
  Alert,
  Button,
  ColumnLayout,
  KeyValuePairs,
  Icon,
} from '@cloudscape-design/components';
import { readInventory } from '../agentcore';
import { useSplitPanel } from '../SplitPanelContext';
import { getStatusConfig, getAlertConfig, PRIORITY_COLORS } from '../constants';

function GenAiLabel() {
  return (
    <Box variant="awsui-gen-ai-label" fontSize="body-s">
      <Icon name="gen-ai" size="small" />
      Generated by AI
    </Box>
  );
}

interface FunctionRecord {
  function_arn: string;
  region: string;
  runtime: string;
  target_runtime?: string;
  alert_status?: string;
  migration_complexity?: string;
  migration_status?: string;
  priority_score?: number;
  tags?: Record<string, string>;
  invocation_count_14d?: number;
  avg_daily_invokes?: number;
  last_invocation_date?: string;
  deprecation_date?: string;
  days_to_deprecation?: number;
  package_type?: string;
  memory_size?: number;
  timeout?: number;
  handler?: string;
  code_size?: number;
  architectures?: string[];
  layers?: string[];
  env_vars?: Record<string, string>;
  ta_last_updated?: string;
  [key: string]: unknown;
}

type SortingColumn = { sortingField: string };

function extractFunctionName(arn: string): string {
  const match = arn.match(/function:(.+)/);
  return match ? match[1] : arn;
}

function formatDate(dateStr?: string): string {
  if (!dateStr) return '—';
  try {
    return new Date(dateStr).toLocaleDateString(undefined, {
      year: 'numeric', month: 'short', day: 'numeric',
    });
  } catch { return dateStr; }
}

function formatBytes(bytes?: number): string {
  if (!bytes) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

const COLUMN_DEFINITIONS = [
  {
    id: 'function_name', header: 'Function Name',
    cell: (item: FunctionRecord) => extractFunctionName(item.function_arn),
    sortingField: 'function_arn', width: 260,
  },
  {
    id: 'region', header: 'Region',
    cell: (item: FunctionRecord) => item.region || '—',
    sortingField: 'region', width: 130,
  },
  {
    id: 'runtime', header: 'Runtime',
    cell: (item: FunctionRecord) => item.runtime || '—',
    sortingField: 'runtime', width: 120,
  },
  {
    id: 'alert_status', header: 'Alert',
    cell: (item: FunctionRecord) => {
      const cfg = getAlertConfig(item.alert_status || '');
      return <Badge color={cfg.color as any}>{cfg.label}</Badge>;
    },
    sortingField: 'alert_status', width: 90,
  },
  {
    id: 'migration_status', header: 'Status',
    cell: (item: FunctionRecord) => {
      const st = item.migration_status || 'DISCOVERED';
      const cfg = getStatusConfig(st);
      return <StatusIndicator type={cfg.type}>{cfg.label}</StatusIndicator>;
    },
    sortingField: 'migration_status', width: 140,
  },
  {
    id: 'priority_score', header: (<>Priority <Icon name="gen-ai" size="small" /></>),
    cell: (item: FunctionRecord) => {
      const label = (item as any).priority_label || '—';
      if (label === '—') return <>—</>;
      return <Badge color={PRIORITY_COLORS[label] as any || 'grey'}>{label}</Badge>;
    },
    sortingField: 'priority_score', width: 120,
  },
];

const PAGE_SIZE = 20;

function FunctionDetailPanel({ item }: { item: FunctionRecord }) {
  const tags = item.tags || {};
  const layers = item.layers || [];
  const envVars = item.env_vars || {};

  return (
    <ColumnLayout columns={4} variant="text-grid">
        <SpaceBetween size="s">
          <Header variant="h3" description='We use the "AWS Lambda Functions Using Deprecated Runtimes" (L4dfs2Q4C5) AWS Support API Security Check to fetch the below data'>Source: AWS Trusted Advisor</Header>
          <KeyValuePairs columns={1} items={[
            { label: 'Region', value: item.region || '—' },
            { label: 'Runtime', value: item.runtime || '—' },
            { label: 'Alert', value: (() => { const c = getAlertConfig(item.alert_status || ''); return <Badge color={c.color as any}>{c.label}</Badge>; })() },
            { label: 'Deprecation', value: item.deprecation_date || '—' },
            { label: 'Days', value: item.days_to_deprecation != null ? String(item.days_to_deprecation) : '—' },
            { label: 'Avg Daily Invokes', value: item.avg_daily_invokes != null ? item.avg_daily_invokes.toFixed(2) : '—' },
          ]} />
        </SpaceBetween>
        <SpaceBetween size="s">
          <Header variant="h3" description="We use GetFunctionConfiguration and ListTags API Actions to fetch the below data">Source: AWS Lambda</Header>
          <KeyValuePairs columns={1} items={[
            { label: 'Handler', value: item.handler || '—' },
            { label: 'Package', value: item.package_type || '—' },
            { label: 'Architecture', value: (item.architectures || ['x86_64']).join(', ') },
            { label: 'Memory', value: item.memory_size ? `${item.memory_size} MB` : '—' },
            { label: 'Timeout', value: item.timeout ? `${item.timeout}s` : '—' },
            { label: 'Code Size', value: formatBytes(item.code_size) },
            { label: 'Tags', value: Object.keys(tags).length > 0 ? Object.entries(tags).map(([k, v]) => `${k}=${v}`).join(', ') : 'None' },
            { label: 'Layers', value: layers.length > 0 ? String(layers.length) : 'None' },
            { label: 'Env Vars', value: Object.keys(envVars).length > 0 ? Object.keys(envVars).join(', ') : 'None' },
          ]} />
        </SpaceBetween>
        <SpaceBetween size="s">
          <Header variant="h3" description="We use DescribeLogStreams and GetMetricStatistics API Actions to fetch the below data">Source: Amazon CloudWatch</Header>
          <KeyValuePairs columns={1} items={[
            { label: 'Last Invoked', value: formatDate(item.last_invocation_date) },
            { label: 'Invocations (14d)', value: item.invocation_count_14d != null ? item.invocation_count_14d.toLocaleString() : '—' },
          ]} />
        </SpaceBetween>
        <SpaceBetween size="s">
          <Header variant="h3" description="AI-powered migration priority scoring based on deprecation urgency, invocation patterns, environment tags, and runtime age — Amazon Nova 2 Lite via Converse API">Source: Amazon Bedrock</Header>
          <GenAiLabel />
          <KeyValuePairs columns={1} items={[
            { label: 'Priority', value: (() => { const l = (item as any).priority_label || '—'; return <Badge color={PRIORITY_COLORS[l] as any || 'grey'}>{l}</Badge>; })() },
            { label: 'Score', value: item.priority_score != null ? `${item.priority_score}/100` : '—' },
            { label: 'Reasoning', value: (item as any).priority_reasoning || '—' },
            { label: 'Status', value: (() => { const c = getStatusConfig(item.migration_status || 'DISCOVERED'); return <StatusIndicator type={c.type}>{c.label}</StatusIndicator>; })() },
          ]} />
        </SpaceBetween>
      </ColumnLayout>
  );
}

export default function Functions() {
  const navigate = useNavigate();
  const { openPanel } = useSplitPanel();
  const [functions, setFunctions] = useState<FunctionRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filterText, setFilterText] = useState('');
  const [sortingColumn, setSortingColumn] = useState<SortingColumn>({ sortingField: 'function_arn' });
  const [sortingDescending, setSortingDescending] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [selectedItems, setSelectedItems] = useState<FunctionRecord[]>([]);

  async function loadFunctions() {
    setLoading(true);
    setError(null);
    try {
      let result = await readInventory();
      if (typeof result === 'string') {
        try { result = JSON.parse(result); } catch { /* keep */ }
      }
      const typed = result as { functions: FunctionRecord[] } | null;
      setFunctions(typed?.functions || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load functions');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadFunctions(); }, []);

  // Open split panel when selection changes
  useEffect(() => {
    if (selectedItems.length > 0) {
      const item = selectedItems[0];
      openPanel(
        extractFunctionName(item.function_arn),
        <FunctionDetailPanel key={item.function_arn} item={item} />,
      );
    }
  }, [selectedItems]);

  const filteredItems = useMemo(() => {
    if (!filterText) return functions;
    const lower = filterText.toLowerCase();
    return functions.filter((fn) => {
      const name = extractFunctionName(fn.function_arn).toLowerCase();
      const runtime = (fn.runtime || '').toLowerCase();
      const region = (fn.region || '').toLowerCase();
      const status = (fn.migration_status || '').toLowerCase();
      return name.includes(lower) || runtime.includes(lower) || region.includes(lower) || status.includes(lower);
    });
  }, [functions, filterText]);

  const sortedItems = useMemo(() => {
    const field = sortingColumn.sortingField as keyof FunctionRecord;
    const sorted = [...filteredItems].sort((a, b) => {
      const aVal = a[field]; const bVal = b[field];
      if (aVal == null && bVal == null) return 0;
      if (aVal == null) return 1; if (bVal == null) return -1;
      if (typeof aVal === 'number' && typeof bVal === 'number') return aVal - bVal;
      return String(aVal).localeCompare(String(bVal));
    });
    return sortingDescending ? sorted.reverse() : sorted;
  }, [filteredItems, sortingColumn, sortingDescending]);

  const totalPages = Math.max(1, Math.ceil(sortedItems.length / PAGE_SIZE));
  const paginatedItems = sortedItems.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  if (loading) {
    return (
      <Box textAlign="center" padding={{ top: 'xxxl' }}>
        <Spinner size="large" />
        <Box variant="p" padding={{ top: 's' }}>Loading functions...</Box>
      </Box>
    );
  }

  return (
    <Table
      header={
        <Header variant="h1" counter={`(${filteredItems.length})`}
          actions={
            <SpaceBetween size="xs" direction="horizontal">
              <Button onClick={() => { if (selectedItems.length > 0) navigate(`/functions/${encodeURIComponent(selectedItems[0].function_arn)}`); }}
                disabled={selectedItems.length === 0} iconName="external">
                View Details
              </Button>
              <Button onClick={loadFunctions} iconName="refresh">Refresh</Button>
            </SpaceBetween>
          }>
          Functions
        </Header>
      }
      columnDefinitions={COLUMN_DEFINITIONS}
      items={paginatedItems}
      trackBy="function_arn"
      selectionType="single"
      selectedItems={selectedItems}
      onSelectionChange={({ detail }) => setSelectedItems(detail.selectedItems as FunctionRecord[])}
      sortingColumn={sortingColumn}
      sortingDescending={sortingDescending}
      onSortingChange={(event) => {
        setSortingColumn(event.detail.sortingColumn as SortingColumn);
        setSortingDescending(event.detail.isDescending ?? false);
        setCurrentPage(1);
      }}
      filter={
        <TextFilter filteringText={filterText} filteringPlaceholder="Search functions..."
          onChange={(event: { detail: { filteringText: string } }) => { setFilterText(event.detail.filteringText); setCurrentPage(1); }} />
      }
      pagination={
        <Pagination currentPageIndex={currentPage} pagesCount={totalPages}
          onChange={(event: { detail: { currentPageIndex: number } }) => setCurrentPage(event.detail.currentPageIndex)} />
      }
      empty={
        <Box textAlign="center" padding={{ top: 'l' }}>
          <SpaceBetween size="m">
            {error ? (
              <Alert type="error">{error}</Alert>
            ) : (
              <Box variant="p" color="text-status-inactive">
                No functions found. Trigger a scan from the Dashboard or click Refresh.
              </Box>
            )}
          </SpaceBetween>
        </Box>
      }
      stickyHeader variant="full-page"
    />
  );
}
