import { useState, useEffect } from 'react';
import {
  Box,
  Button,
  Container,
  Header,
  SpaceBetween,
  Spinner,
  Alert,
  Icon,
  ColumnLayout,
  KeyValuePairs,
  Badge,
} from '@cloudscape-design/components';
import { readInventory } from '../agentcore';
import { PRIORITY_COLORS } from '../constants';

function GenAiLabel() {
  return (
    <Box variant="awsui-gen-ai-label" fontSize="body-s">
      <Icon name="gen-ai" size="small" />
      Generated by AI
    </Box>
  );
}

interface FunctionRecord {
  function_arn: string;
  runtime?: string;
  target_runtime?: string;
  migration_complexity?: string;
  migration_status?: string;
  alert_status?: string;
  priority_score?: number;
  priority_label?: string;
  priority_reasoning?: string;
  days_to_deprecation?: number;
  invocation_count_14d?: number;
  avg_daily_invokes?: number;
  tags?: Record<string, string>;
  lines_of_code?: number;
  assessed_at?: string;
  transformed_at?: string;
  [key: string]: unknown;
}

function extractFunctionName(arn: string): string {
  return arn.match(/function:(.+)/)?.[1]?.split(':')[0] || arn;
}


// Generate the plan structure from inventory data and format as a rich report.
// The AI prioritization already happened in Phase 1 — we organize the results
// into actionable migration waves based on priority + complexity.
function generatePlanLocally(functions: FunctionRecord[]): {
  summary: { total: number; assessed: number; transformed: number; critical: number; high: number; medium: number; low: number; inactive: number; byRuntime: Record<string, number>; byComplexity: Record<string, number>; totalLoc: number };
  waves: { name: string; description: string; functions: FunctionRecord[] }[];
  markdown: string;
} {
  const active = functions.filter(f => f.migration_status !== 'RESOLVED' && f.migration_status !== 'SKIPPED');
  
  const summary = {
    total: active.length,
    assessed: active.filter(f => f.assessed_at).length,
    transformed: active.filter(f => f.transformed_at).length,
    critical: active.filter(f => f.priority_label === 'CRITICAL').length,
    high: active.filter(f => f.priority_label === 'HIGH').length,
    medium: active.filter(f => f.priority_label === 'MEDIUM').length,
    low: active.filter(f => f.priority_label === 'LOW').length,
    inactive: active.filter(f => f.priority_label === 'INACTIVE').length,
    byRuntime: {} as Record<string, number>,
    byComplexity: {} as Record<string, number>,
    totalLoc: 0,
  };

  for (const fn of active) {
    const rt = fn.runtime || 'unknown';
    summary.byRuntime[rt] = (summary.byRuntime[rt] || 0) + 1;
    if (fn.migration_complexity) {
      summary.byComplexity[fn.migration_complexity] = (summary.byComplexity[fn.migration_complexity] || 0) + 1;
    }
    summary.totalLoc += (fn.lines_of_code || 0);
  }

  // Build migration waves based on priority + complexity
  const wave1 = active.filter(f => 
    (f.priority_label === 'CRITICAL' || f.priority_label === 'HIGH') && 
    (f.migration_complexity === 'LOW' || !f.migration_complexity)
  ).sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0));

  const wave2 = active.filter(f =>
    !wave1.includes(f) &&
    ((f.priority_label === 'CRITICAL' || f.priority_label === 'HIGH') || f.migration_complexity === 'MEDIUM')
  ).sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0));

  const wave3 = active.filter(f =>
    !wave1.includes(f) && !wave2.includes(f) && f.migration_complexity === 'HIGH'
  ).sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0));

  const wave4 = active.filter(f =>
    !wave1.includes(f) && !wave2.includes(f) && !wave3.includes(f)
  ).sort((a, b) => (b.priority_score || 0) - (a.priority_score || 0));

  const waves = [
    { name: 'Wave 1 — Quick Wins', description: 'Critical/High priority with Low complexity. Migrate immediately with minimal risk.', functions: wave1 },
    { name: 'Wave 2 — Medium Effort', description: 'Critical/High priority with Medium complexity, or Medium priority functions. Requires some code changes.', functions: wave2 },
    { name: 'Wave 3 — Major Refactoring', description: 'High complexity functions requiring significant code changes. Plan dedicated sprint time.', functions: wave3 },
    { name: 'Wave 4 — Low Priority', description: 'Low priority or inactive functions. Consider cleanup or deferred migration.', functions: wave4 },
  ].filter(w => w.functions.length > 0);

  // Build markdown report
  let md = `## Executive Summary\n\n`;
  md += `This migration plan covers **${summary.total} Lambda functions** running deprecated runtimes.\n\n`;
  md += `| Metric | Value |\n|---|---|\n`;
  md += `| Total Functions | ${summary.total} |\n`;
  md += `| Assessed (Phase 2) | ${summary.assessed} |\n`;
  md += `| Transformed (Phase 3) | ${summary.transformed} |\n`;
  md += `| Total Lines of Code | ${summary.totalLoc.toLocaleString()} |\n`;
  md += `\n### Priority Distribution\n\n`;
  md += `| Priority | Count |\n|---|---|\n`;
  if (summary.critical) md += `| 🔴 Critical | ${summary.critical} |\n`;
  if (summary.high) md += `| 🟠 High | ${summary.high} |\n`;
  if (summary.medium) md += `| 🟡 Medium | ${summary.medium} |\n`;
  if (summary.low) md += `| 🟢 Low | ${summary.low} |\n`;
  if (summary.inactive) md += `| ⚪ Inactive | ${summary.inactive} |\n`;
  md += `\n### Runtime Distribution\n\n`;
  md += `| Runtime | Count |\n|---|---|\n`;
  for (const [rt, count] of Object.entries(summary.byRuntime).sort((a, b) => b[1] - a[1])) {
    md += `| ${rt} | ${count} |\n`;
  }
  if (Object.keys(summary.byComplexity).length > 0) {
    md += `\n### Complexity Distribution\n\n`;
    md += `| Complexity | Count |\n|---|---|\n`;
    for (const [cx, count] of Object.entries(summary.byComplexity)) {
      md += `| ${cx} | ${count} |\n`;
    }
  }

  md += `\n---\n\n## Migration Waves\n\n`;
  for (const wave of waves) {
    md += `### ${wave.name}\n\n`;
    md += `${wave.description}\n\n`;
    md += `| Function | Runtime | Target | Complexity | Priority | Status |\n|---|---|---|---|---|---|\n`;
    for (const fn of wave.functions) {
      const name = extractFunctionName(fn.function_arn);
      md += `| ${name} | ${fn.runtime || '—'} | ${fn.target_runtime || '—'} | ${fn.migration_complexity || '—'} | ${fn.priority_label || '—'} (${fn.priority_score || 0}) | ${fn.migration_status || '—'} |\n`;
    }
    md += `\n`;
    // Add AI reasoning for each function
    const withReasoning = wave.functions.filter(f => f.priority_reasoning);
    if (withReasoning.length > 0) {
      md += `**AI Reasoning:**\n\n`;
      for (const fn of withReasoning) {
        md += `- **${extractFunctionName(fn.function_arn)}**: ${fn.priority_reasoning}\n`;
      }
      md += `\n`;
    }
  }

  md += `---\n\n## Recommendations\n\n`;
  
  const skipped = functions.filter(f => f.migration_status === 'SKIPPED');
  const resolved = functions.filter(f => f.migration_status === 'RESOLVED');
  const inactive = active.filter(f => f.priority_label === 'INACTIVE');
  
  if (inactive.length > 0) {
    md += `### Cleanup Candidates\n\n`;
    md += `${inactive.length} function(s) have no recent invocations. Consider deleting instead of migrating:\n\n`;
    for (const fn of inactive) {
      md += `- **${extractFunctionName(fn.function_arn)}** (${fn.runtime}) — ${fn.priority_reasoning || 'No recent invocations'}\n`;
    }
    md += `\n`;
  }
  if (skipped.length > 0) {
    md += `### Container Image Functions (Skipped)\n\n`;
    md += `${skipped.length} function(s) use container image packaging and cannot be migrated via code transformation. Update the container base image instead.\n\n`;
  }
  if (resolved.length > 0) {
    md += `### Resolved Functions\n\n`;
    md += `${resolved.length} function(s) are no longer flagged by Trusted Advisor (already migrated or deleted).\n\n`;
  }

  return { summary, waves, markdown: md };
}

export default function MigrationPlan() {
  const [functions, setFunctions] = useState<FunctionRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [plan, setPlan] = useState<ReturnType<typeof generatePlanLocally> | null>(null);

  useEffect(() => {
    async function load() {
      try {
        let result = await readInventory();
        if (typeof result === 'string') try { result = JSON.parse(result); } catch { /* */ }
        const typed = result as { functions: FunctionRecord[] } | null;
        const fns = typed?.functions || [];
        setFunctions(fns);
        if (fns.length > 0) {
          setPlan(generatePlanLocally(fns));
        }
      } catch { /* */ }
      finally { setLoading(false); }
    }
    load();
  }, []);

  function handleRefresh() {
    setLoading(true);
    readInventory().then(result => {
      if (typeof result === 'string') try { result = JSON.parse(result); } catch { /* */ }
      const typed = result as { functions: FunctionRecord[] } | null;
      const fns = typed?.functions || [];
      setFunctions(fns);
      if (fns.length > 0) setPlan(generatePlanLocally(fns));
    }).finally(() => setLoading(false));
  }

  if (loading) {
    return <Box textAlign="center" padding="xxxl"><Spinner size="large" /><Box variant="p" padding={{ top: 's' }}>Loading migration plan...</Box></Box>;
  }

  if (!plan || functions.length === 0) {
    return (
      <SpaceBetween size="l">
        <Header variant="h1" actions={<Button onClick={handleRefresh} iconName="refresh">Refresh</Button>}>Migration Plan</Header>
        <Box textAlign="center" padding="xxxl" color="text-status-inactive">
          No functions in inventory. Run a Scan from the Dashboard first.
        </Box>
      </SpaceBetween>
    );
  }

  const s = plan.summary;

  return (
    <SpaceBetween size="l">
      <Header variant="h1"
        description="AI-prioritized migration plan with wave-based execution strategy"
        actions={<Button onClick={handleRefresh} iconName="refresh">Refresh</Button>}
      >
        Migration Plan
      </Header>

      {/* KPI Cards */}
      <ColumnLayout columns={4} variant="text-grid">
        <Container>
          <KeyValuePairs columns={1} items={[
            { label: 'Total Functions', value: <Box variant="h1" fontSize="display-l">{s.total}</Box> },
            { label: 'Lines of Code', value: s.totalLoc.toLocaleString() },
          ]} />
        </Container>
        <Container>
          <KeyValuePairs columns={1} items={[
            { label: 'Assessed', value: `${s.assessed} / ${s.total}` },
            { label: 'Transformed', value: `${s.transformed} / ${s.total}` },
          ]} />
        </Container>
        <Container>
          <GenAiLabel />
          <KeyValuePairs columns={1} items={[
            { label: 'Critical', value: <Badge color={PRIORITY_COLORS.CRITICAL as any}>{s.critical}</Badge> },
            { label: 'High', value: <Badge color={PRIORITY_COLORS.HIGH as any}>{s.high}</Badge> },
            { label: 'Medium', value: <Badge color={PRIORITY_COLORS.MEDIUM as any}>{s.medium}</Badge> },
          ]} />
        </Container>
        <Container>
          <KeyValuePairs columns={1} items={[
            { label: 'Low', value: <Badge color={PRIORITY_COLORS.LOW as any}>{s.low}</Badge> },
            { label: 'Inactive', value: <Badge color={PRIORITY_COLORS.INACTIVE as any}>{s.inactive}</Badge> },
          ]} />
        </Container>
      </ColumnLayout>

      {/* Wave Cards */}
      {plan.waves.map((wave, idx) => (
        <Container key={idx} header={
          <Header variant="h3" description={wave.description} counter={`(${wave.functions.length})`}>
            {wave.name}
          </Header>
        }>
          <SpaceBetween size="s">
            {wave.functions.map(fn => (
              <Box key={fn.function_arn} padding={{ vertical: 'xxs' }}>
                <SpaceBetween size="xs" direction="horizontal">
                  <Badge color={PRIORITY_COLORS[fn.priority_label || ''] as any || 'grey'}>{fn.priority_label}</Badge>
                  <Box variant="code" fontSize="body-s">{extractFunctionName(fn.function_arn)}</Box>
                  <Box color="text-body-secondary" fontSize="body-s">{fn.runtime} → {fn.target_runtime || '?'}</Box>
                  {fn.migration_complexity && <Badge color={fn.migration_complexity === 'HIGH' ? 'severity-high' : fn.migration_complexity === 'MEDIUM' ? 'severity-medium' : 'severity-low' as any}>{fn.migration_complexity}</Badge>}
                </SpaceBetween>
                {fn.priority_reasoning && <Box fontSize="body-s" color="text-body-secondary" padding={{ left: 'l' }}>{fn.priority_reasoning}</Box>}
              </Box>
            ))}
          </SpaceBetween>
        </Container>
      ))}

    </SpaceBetween>
  );
}
